<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>59842858-14f7-4955-8e15-c9168852f161</testSuiteGuid>
   <testCaseLink>
      <guid>8080d207-6ad1-4a22-9a8f-44d399f03dbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>090bab7a-6903-4fea-834a-f1b5c8892508</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TC_Login/Login details</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>090bab7a-6903-4fea-834a-f1b5c8892508</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>e870d8e5-cb08-4ef6-993d-3db2955493db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>090bab7a-6903-4fea-834a-f1b5c8892508</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>91b3d405-e7b2-46ab-abae-688c5b00983e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
